### PR TITLE
Fix the bugs occur on MVP and added loading UI in index

### PR DESCRIPTION
**Pull request by rikashi-shifu**
### Please tell us what you did
1. Fix the search bar where the query is not changing on the URL when I click on the clear button
2. Fix some responsive styling for smaller devices
3. Added animation for the search bar on the index page
4. Added loading UI for the index page to push the path "/search" with user input query

### Are there any concerns that may be raised?
To fix the 1. issue, I had to change "defaultValue" to "value" which causes this warning: "A component is changing a controlled input to be uncontrolled"

### Please add which issue does this PR close below using ("closes #issue_number")
None

### CODE REVIEW

**Comment by ETCasual** [comment]
did u pull from main before you push ? @rikashi-shifu

**Comment by rikashi-shifu** [comment]
I think no

**Comment by ETCasual** [comment]
Please pull from main again ya, got major changes to `schema.prisma` as we change db from `mysql` to `postgresql`

**Comment by ETCasual** [comment]
Fixed a bug on `undefined` return when the dependent data is returned after the UI is rendered.

Fix by memoizing `filteredSongList` according to dependent data.

**Review by ETCasual — APPROVED** [review]
LGTM.

**Pull request merged**
